todo/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^todo/', include('todo_app.urls', namespace='todo', app_name='todo_app')),
]

todo_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.todo_list, name='todo_list'),
    url(r'^new/$', views.new_post, name='new_post'),
    url(r'^form/$', views.post_form, name='post_form'),
    url(r'^(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
]

todo_app/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver

# Create your models here.

class Todo(models.Model):
    name = models.CharField(db_column='Name', max_length=50)
    description = models.TextField(db_column='Description',max_length=150)

    class Meta:
        managed = True
        db_table = "Todo"

    def get_absolute_url(self):
     return reverse('todo_app:post_detail', args=[self.id])

    def __str__(self):
        return self.name

class TodoMirror(models.Model):
    id = models.OneToOneField(Todo,primary_key=True, on_delete=models.CASCADE)
    mname = models.CharField(max_length=50, blank=True)
    mdescription = models.TextField(max_length=150, blank=True)

    class Meta:
        managed = True
        db_table = 'TodoMirror'

    def __str__(self):
        return self.mname

@receiver(post_save, sender=Todo)
def create_mirror_obj(sender, instance, created, **kwargs):
    if created:
        obj = TodoMirror.objects.create(id=instance,mname=instance.name,
                                    mdescription=instance.description)
        obj.save()
    if not created:
        TodoMirror.objects.filter(id=instance).update(mname=instance.name)
        TodoMirror.objects.filter(id=instance).update(mdescription=instance.description)
        pass

@receiver(post_save, sender=TodoMirror)
def create_todo_obj(sender, instance, created, **kwargs):
    if not created:
        Todo.objects.filter(id=instance.id.id).update(name=instance.mname)
        Todo.objects.filter(id=instance.id.id).update(description=instance.mdescription)
        pass

@receiver(post_delete, sender=TodoMirror)
def delete_todo_obj(sender, instance, **kwargs):
    obj = Todo.objects.get(id=instance.id.id)
    obj.delete()

todo_app/views.py
from django.conf import settings
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from . models import Todo, TodoMirror
from django.core.urlresolvers import reverse

# Create your views here.
def post_form(request):
    return render(request, 'todo_app/post/new_post.html')

def post_detail(request, pk):
    post = get_object_or_404(Todo, id=pk)
    return render(request, 'todo_app/post/detail.html', {'post': post})

def todo_list(request):
    object_list = Todo.objects.all()

    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)

    return render(request, 'todo_app/post/list.html', {'page': page, 'posts': posts})

def new_post(request):
    if request.method == 'POST':
        pname = request.POST.get('name')
        pdescription = request.POST.get('description')
        post, created = Todo.objects.get_or_create(name=pname,
                                description=pdescription)
        print(post.id)
        post.save()
    else:
        return render(request, 'todo_app/post/new_post.html')
    return render(request, 'todo_app/post/detail.html', {'post': post})

todo_app/templates/todo_app/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
      <title>{% block title %}{% endblock %}</title>
      <!---bootstarp --->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

      <!--- javascript for bbotstarp--->
      <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
      <script src="{% static 'JS/jquery-3.2.1.js' %}"></script>

      <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

      <!-- Medium style editing -->
      <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
      <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">

      <!-- Custom CSS -->
      <link href="{% static "css/todo.css" %}" rel="stylesheet">
  </head>
  <body>
    <div id="header">
      <span class="logo">
        <a href="{% url 'todo_app:todo_list' %}" style="color:#f3f7cc;">TODO</a>
      </span>
      <span id="new">
        <a href="{% url 'todo_app:post_form' %}" style="color:#f3f7cc;">New Memo</a>
      </span>
    </div>
    <div id="main">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

todo_app/templates/todo_app/pagination.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}
    <span class="current">
      Page {{ page.number }} of {{ page.paginator.num_pages }}
    </span>
      {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
      {% endif %}
  </span>
</div>

todo_app/templates/todo_app/post/detail.html
{% extends "todo_app/base.html" %}

{% block title %}{{ post.name }}{% endblock %}

{% block content %}
  <h1>{{ post.name }}</h1>
  {{ post.description|truncatewords:30 }}
{% endblock %}

todo_app/templates/todo_app/post/list.html
{% extends "todo_app/base.html" %}
{% block title %}
TODO
{% endblock %}

{% block content %}
  {% for post in posts %}
    <h2>
      <a href="{{ post.get_absolute_url }}">
        {{ post.name }}
      </a>
    </h2>
  {% endfor %}
  {% include "pagination.html" with page=posts %}
{% endblock %}

todo_app/templates/todo_app/post/new_post.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}


<h1>New Post</h1>

<form enctype="multipart/form-data" action="{% url 'todo_app:new_post' %}" method="POST">
  {% csrf_token %}
  <p>
    <label>Name: <br>
      <input type="text" name="name" class="textinputclass">
    </label>
    <label>Description: <br>
      <textarea name="description" rows="8" cols="80" class="editable medium-editors-textarea"></textarea>
    </label> <br>
    <p><button type="submit" class="save btn btn-default">Save</button></p>
  </p>
</form>

{% endblock %}